# Generated by Django 3.2.6 on 2023-03-01 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscribemodel',
            old_name='creator',
            new_name='other_user',
        ),
        migrations.RenameField(
            model_name='subscribemodel',
            old_name='subscriber',
            new_name='self_user',
        ),
    ]
